# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.define "pyddit" do |config|
    # pour pyramid
    config.vm.network :forwarded_port, guest: 6543, host: 6543
    # pour django
    config.vm.network :forwarded_port, guest: 8080, host: 8080

    config.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "init.pp"
    end

    config.vm.synced_folder "../src/pyramid", "/opt/pyramid"
    config.vm.synced_folder "../src/django", "/opt/django"
  end
end
